INSERT INTO Basketball_Teams (Id, City, Team_Name, PG,SG,SF,PF,C,Coach,Momentum,Timezone)
VALUES (1, 'Atlanta', 'Hawks','A','C+','C','C+','A-','B','Neutral',1),
 (2, 'Washington', 'Wizards','D','A-','D','D-','A-','B','Neutral',1),
 (3, 'Orlando', 'Magic','D-','D-','C','D','D+','C','Neutral',1),
 (4, 'Miami', 'Heat','C-','B-','A+','D-','B','A','Neutral',1),
 (5, 'Charlotte', 'Hornets','B-','D+','C','D','C+','C+','Neutral',1),
(6, 'Milwaukee', 'Bucks','B','C','B-','A+','C+','B','Neutral',2),
 (7, 'Cleveland', 'Cavaliers','B','A+','D','C','B','B','Neutral',1),
 (8, 'Chicago', 'Bulls','C','B','A-','D-','B','C','Neutral',2),
 (9, 'Indiana', 'Pacers','C','C','B','D+','B-','A','Neutral',1),
 (10, 'Detroit', 'Pistons','D+','B','B','C-','D+','C+','Neutral',1),
 (11, 'Philadelphia', '76ers','C','A','B','D','A','B','Neutral',1),
 (12, 'New York', 'Knicks','B+','C','B','B','C+','B','Neutral',1),
 (13, 'Brooklyn', 'Nets','B','D','B+','D-','C','C','Neutral',1),
 (14, 'Boston', 'Celtics','C+','A-','A','D-','B-','A','Neutral',1),
 (15, 'Toronto','Raptors','C+','C+','C+','B','B+','C+','Neutral',1),
 (16, 'Minnesota', 'Timberwolves','D+','B','C','D-','C+','B','Neutral',2),
 (17, 'Oklahoma City', 'Thunder','D','B-','D+','D+','F','B','Neutral',2),
 (18, 'Utah', 'Jazz','C-','B+','D','B+','A-','C','Neutral',3),
 (19, 'Denver', 'Nuggets','B-','D-','B-','C+','A+','A','Neutral',3),
 (20, 'Portland','Trailblazers','A-','D+','C+','C-','D+','C+','Neutral',4),
 (21, 'Sacramento', 'Kings','C','C+','C','A','D-','B','Neutral',4),
 (22, 'Los Angeles', 'Clippers','B','B','B','B','B','B','Neutral',4),
 (23, 'Golden State', 'Warriors','A+','C+','C','C','F','C','Neutral',4),
 (24, 'Los Angeles', 'Lakers','C-','C-','A','A','D+','A','Neutral',4),
 (25, 'Pheonix', 'Suns','B','A','D+','A','B','C+','Neutral',4),
 (26, 'Memphis', 'Grizzles','A-','D-','D-','B+','C-','B','Neutral',2),
 (27, 'New Orleans', 'Pelicans','C','C','B+','D+','D-','B','Neutral',2),
 (28, 'Dallas', 'Maverics','A','D+','D+','D+','D','C','Neutral',2),
 (29, 'Houston', 'Rockets','D-','C','D','D+','C+','A','Neutral',2),
 (30, 'San Antonio', 'Spurs','C+','D-','C','C-','C-','C+','Neutral',2);